name = "tokyonight"
background = "light"

[hues]

[colors]
bg1 = "#f8f9fa"
bg0 = "#e9ecef"

black = "#adb5bd"

bg2 = "#e9ecef"
bg3 = "#dee2e6"
visual_bg = "#dee2e6"

comment = "#868e96"

fg0 = "#495057"
fg1 = "#343a40"
fg2 = "#212529"

red    = "#8c4351"
green  = "#385f0d"
yellow = "#8f5e15"
blue   = "#2959aa"
purple = "#5a3e8e"
cyan   = "#006c86"
orange = "#965027"
teal0  = "#0f4b6e"
teal1  = "#33635c"

diag_ok_bg    = "mix(green, bg1, 0.1)"
diag_info_bg  = "mix(blue, bg1, 0.1)"
diag_hint_bg  = "mix(cyan, bg1, 0.1)"
diag_warn_bg  = "mix(yellow, bg1, 0.1)"
diag_error_bg = "mix(red, bg1, 0.1)"

diff_add_bg    = "mix(green, bg1, 0.2)"
diff_text_bg   = "mix(cyan, bg1, 0.2)"
diff_delete_bg = "mix(red, bg1, 0.2)"

[highlights]
Normal      = "fg1 bg1"
NormalNC    = "fg1 bg1"
NormalFloat = "fg1 bg3"

EndOfBuffer = "bg3"
NonText     = "bg3"
Whitespace  = "bg3"

Cursor        = "bg1 fg1"
Cursorline   = "- bg2"
CursorlineNr = "orange bg2"
ColorColumn  = "- bg2"
Folded       = "fg0 bg2"
LineNr       = "black"
SignColumn   = "link:LineNr"
Visual       = "- visual_bg"
WinSeparator = "bg2"

Pmenu      = "fg1 bg3"
PmenuSbar  = "- bg3"
PmenuSel   = "fg2 black"
PmenuThumb = "- fg0"

StatusLine    = "fg0 bg0"
StatusLineNC  = "black bg0"
TabLine       = "fg0 bg3"
TabLineFill   = "fg1 bg0"
TabLineSelect = "bg0 blue"

Search     = "bg0 orange"
CurSearch  = "bg0 yellow"
IncSearch  = "- - r"
Substitute = "bg0 red"
MatchParen = "- visual_bg"

Added   = "green"
Changed = "cyan"
Removed = "red"

DiffAdd    = "green diff_add_bg"
DiffText   = "cyan diff_text_bg"
DiffDelete = "red diff_delete_bg"

ErrorMsg   = "red"
ModeMsg    = "comment"
MoreMsg    = "cyan"
Question   = "blue"
QuickFixLine = "- bg3 b"
WarningMsg = "yellow"

SpellBad   = "- - u red"
SpellCap   = "- - u yellow"
SpellLocal = "- - u blue"
SpellRare  = "- - u cyan"

# Diagnostics
DiagnosticUnderlineOk    = "- - u green"
DiagnosticUnderlineInfo  = "- - u blue"
DiagnosticUnderlineHint  = "- - u cyan"
DiagnosticUnderlineWarn  = "- - u yellow"
DiagnosticUnderlineError = "- - u red"

DiagnosticOk    = "green diag_ok_bg"
DiagnosticInfo  = "blue diag_info_bg"
DiagnosticHint  = "cyan diag_hint_bg"
DiagnosticWarn  = "yellow diag_warn_bg"
DiagnosticError = "red diag_error_bg"

DiagnosticSignOk    = "green"
DiagnosticSignInfo  = "blue"
DiagnosticSignHint  = "cyan"
DiagnosticSignWarn  = "yellow"
DiagnosticSignError = "red"

# Syntax
Bold         = "fg1 - b"
Character    = "green"
Comment      = "comment"
Constant     = "orange"
Debug        = "orange"
Delimiter    = "fg0"
Directory    = "blue"
Error        = "red"
Function     = "blue"
Identifier   = "yellow"
Include      = "cyan"
Italic       = "fg1 - i"
Keyword      = "purple"
Operator     = "fg2"
PreProc      = "cyan"
Special      = "cyan"
Statement    = "purple"
StorageClass = "purple"
String       = "green"
Structure    = "purple"
Title        = "red"
Todo         = "bg0 yellow"
Type         = "teal0"
Underlined   = "fg1 - u"

# treesitter
"@attribute"             = "link:PreProc"
"@boolean"               = "link:Constant"
"@character"             = "link:String"
"@character.special"     = "link:Constant"
"@comment"               = "link:Comment"
"@comment.todo.comment"  = "link:Todo"
"@conceal"               = "link:Comment"
"@conditional"           = "link:Statement"
"@constant.builtin"      = "link:Type"
"@constant"              = "link:Constant"
"@constant.macro"        = "link:Special"
"@constructor"           = "blue"
"@error"                 = "link:Error"
"@exception"             = "link:Keyword"
"@field"                 = "link:Identifier"
"@float"                 = "link:Constant"
"@function.builtin"      = "link:Function"
"@function"              = "link:Function"
"@function.macro"        = "link:PreProc"
"@include"               = "link:Include"
"@keyword.directive"     = "link:PreProc"
"@keyword.function"      = "link:Keyword"
"@keyword.import"        = "link:Include"
"@keyword"               = "link:Keyword"
"@label"                 = "link:Special"
"@method"                = "link:Function"
"@module"                = "link:Type"
"@namespace"             = "link:Statement"
"@number"                = "link:Constant"
"@operator"              = "link:Operator"
"@parameter"             = "link:Identifier"
"@preproc"               = "link:PreProc"
"@property"              = "teal1"
"@punctuation.bracket"   = "fg0"
"@punctuation.delimiter" = "fg0"
"@punctuation.special"   = "link:Special"
"@repeat"                = "link:Statement"
"@string.escape"         = "link:Special"
"@string"                = "link:String"
"@string.regex"          = "yellow"
"@string.special"        = "link:Special"
"@tag.attribute"         = "teal1"
"@tag"                   = "blue"
"@tag.delimiter"         = "blue"
"@text"                  = "fg1"
"@text.title"            = "link:Title"
"@text.uri"              = "link:Uri"
"@text.warning"          = "link:Todo"
"@type.builtin"          = "link:Type"
"@type.definition"       = "link:Keyword"
"@type"                  = "link:Type"
"@type.qualifier"        = "link:Keyword"
"@variable.builtin"      = "link:Statement"
"@variable"              = "fg2"
"@variable.member"       = "teal1"
"@variable.parameter"    = "link:Identifier"

# Language specific highlights
"@constructor.lua"         = "link:Delimiter"
"@property.json"           = "blue"
"@property.toml"           = "blue"
"@property.yaml"           = "blue"
"@string.csv"              = "fg1"
"@string.special.path.nix" = "teal0"
"@variable.parameter.bash" = "fg2"

# Markup highlights
"@markup.heading.1"  = "red"
"@markup.heading.2"  = "yellow"
"@markup.heading.3"  = "green"
"@markup.heading.4"  = "cyan"
"@markup.heading.5"  = "blue"
"@markup.heading.6"  = "purple"
"@markup.list"       = "green"
"@markup.link.label" = "blue - u"
"@markup.link.url"   = "teal1 - u"
"@markup.raw"        = "teal0"

"@punctuation.special.markdown" = "link:Comment"

# Plugins
CmpItemAbbr              = "fg2"
CmpItemAbbrDeprecated    = "link:Comment"
CmpItemAbbrMatch         = "orange"
CmpItemAbbrMatchFuzzy    = "link:Special"
CmpItemKind              = "link:Special"
CmpItemKindClass         = "link:Type"
CmpItemKindColor         = "link:Special"
CmpItemKindConstant      = "link:Constant"
CmpItemKindConstructor   = "link:@constructor"
CmpItemKindEnum          = "link:Constant" # For variety
CmpItemKindEnumMember    = "link:@property"
CmpItemKindEvent         = "link:Special"
CmpItemKindField         = "fg2"
CmpItemKindFile          = "fg2"
CmpItemKindFolder        = "link:Directory"
CmpItemKindFunction      = "link:Function"
CmpItemKindInterface     = "link:Type"
CmpItemKindKeyword       = "link:Keyword"
CmpItemKindMethod        = "link:Function"
CmpItemKindModule        = "link:Type"
CmpItemKindOperator      = "link:Operator"
CmpItemKindProperty      = "link:@property"
CmpItemKindReference     = "fg2"
CmpItemKindSnippet       = "link:String"
CmpItemKindStruct        = "link:Type"
CmpItemKindText          = "link:String"
CmpItemKindTypeParameter = "link:Identifier"
CmpItemKindUnit          = "link:Constant"
CmpItemKindValue         = "fg2"
CmpItemKindVariable      = "fg2"
CmpItemMenu              = "fg2"

NvimTreeFolderIcon   = "link:Directory"
NvimTreeIndentMarker = "link:Directory"
NvimTreeWindowPicker = "bg0 yellow b"
NvimTreeRootFolder   = "purple"
NvimTreeSpecialFile  = "orange"
NvimTreeExecFile     = "green"
NvimTreeDeletedIcon  = "red"
NvimTreeGitMergeIcon = "orange"
NvimTreeGitDirtyIcon = "red"

TelescopeBorder        = "link:Comment"
TelescopeTitle         = "fg2"
TelescopePromptCounter = "link:LineNr"
TelescopeMatching      = "orange"

IblWhitespace = "link:NonText"
IblScope      = "link:LineNr"

[globals]
terminal_color_0          = "bg3"
terminal_color_1          = "red"
terminal_color_2          = "green"
terminal_color_3          = "orange"
terminal_color_4          = "blue"
terminal_color_5          = "purple"
terminal_color_6          = "cyan"
terminal_color_7          = "fg1"
terminal_color_8          = "comment"
terminal_color_9          = "red"
terminal_color_10         = "green"
terminal_color_11         = "orange"
terminal_color_12         = "blue"
terminal_color_13         = "purple"
terminal_color_14         = "cyan"
terminal_color_15         = "fg2"
terminal_color_background = "bg1"
terminal_color_foreground = "fg1"
