name = "tokyonight"
background = "light"

[hues]

[colors]
base_bg = "#e6e7ed"

bg0 = "darken(base_bg, 0.05)"
bg1 = "base_bg"
bg2 = "darken(bg1, 0.05)"
bg3 = "darken(bg1, 0.1)"
bg4 = "darken(bg1, 0.2)"

comment = "#6c6e75"

fg0 = "#40434f"
fg1 = "#343b58"
fg2 = "darken(fg1, 0.05)"

red    = "#8c4351"
green  = "#385f0d"
yellow = "#8f5e15"
blue   = "#2959aa"
purple = "#5a3e8e"
cyan   = "#0f4b6e"
orange = "#965027"
teal0  = "#006c86"
teal1  = "#33635c"

visual_bg = "adjust(bg1, 0.10, -0.1)"

diag_ok_bg    = "mix(green, bg1, 0.1)"
diag_info_bg  = "mix(blue, bg1, 0.1)"
diag_hint_bg  = "mix(teal0, bg1, 0.1)"
diag_warn_bg  = "mix(yellow, bg1, 0.1)"
diag_error_bg = "mix(red, bg1, 0.1)"

diff_add_bg    = "mix(green, bg1, 0.2)"
diff_text_bg   = "mix(teal0, bg1, 0.2)"
diff_delete_bg = "mix(red, bg1, 0.2)"

[highlights]
Normal      = "fg1 bg1"
NormalNC    = "fg1 bg1"
NormalFloat = "fg1 bg0"

EndOfBuffer = "bg3"
NonText     = "bg3"
Whitespace  = "bg3"

Cursor        = "bg1 fg1"
Cursorline   = "- bg2"
CursorlineNr = "orange bg2"
ColorColumn  = "- bg2"
Folded       = "fg0 bg2"
LineNr       = "bg4"
SignColumn   = "link:LineNr"
Visual       = "- visual_bg"
WinSeparator = "bg0 bg0"

Pmenu      = "fg1 bg3"
PmenuSbar  = "- bg3"
PmenuSel   = "fg2 bg4"
PmenuThumb = "- fg0"

StatusLine    = "fg0 bg0"
StatusLineNC  = "bg4 bg0"
TabLine       = "fg0 bg3"
TabLineFill   = "fg1 bg0"
TabLineSelect = "bg0 blue"

Search     = "bg0 orange"
CurSearch  = "bg0 yellow"
IncSearch  = "- - r"
Substitute = "bg0 red"
MatchParen = "- visual_bg"

Added   = "green"
Changed = "teal0"
Removed = "red"

DiffAdd    = "green diff_add_bg"
DiffText   = "teal0 diff_text_bg"
DiffDelete = "red diff_delete_bg"

ErrorMsg   = "red"
ModeMsg    = "comment"
MoreMsg    = "teal0"
Question   = "blue"
QuickFixLine = "- bg3 b"
WarningMsg = "yellow"

SpellBad   = "- - u red"
SpellCap   = "- - u yellow"
SpellLocal = "- - u blue"
SpellRare  = "- - u teal0"

# Diagnostics
DiagnosticUnderlineOk    = "- - u green"
DiagnosticUnderlineInfo  = "- - u blue"
DiagnosticUnderlineHint  = "- - u teal0"
DiagnosticUnderlineWarn  = "- - u yellow"
DiagnosticUnderlineError = "- - u red"

DiagnosticOk    = "green diag_ok_bg"
DiagnosticInfo  = "blue diag_info_bg"
DiagnosticHint  = "teal0 diag_hint_bg"
DiagnosticWarn  = "yellow diag_warn_bg"
DiagnosticError = "red diag_error_bg"

DiagnosticSignOk    = "green"
DiagnosticSignInfo  = "blue"
DiagnosticSignHint  = "teal0"
DiagnosticSignWarn  = "yellow"
DiagnosticSignError = "red"

# Syntax
Bold         = "fg1 - b"
Character    = "green"
Comment      = "comment"
Constant     = "orange"
Debug        = "orange"
Delimiter    = "fg0"
Directory    = "blue"
Error        = "red"
Function     = "blue"
Identifier   = "yellow"
Include      = "cyan"
Italic       = "fg1 - i"
Keyword      = "purple"
Operator     = "cyan"
PreProc      = "cyan"
Special      = "cyan"
Statement    = "purple"
StorageClass = "purple"
String       = "green"
Structure    = "purple"
Title        = "red"
Todo         = "bg0 yellow"
Type         = "teal0"
Underlined   = "fg1 - u"

# treesitter
"@attribute"             = "link:PreProc"
"@boolean"               = "link:Constant"
"@character"             = "link:String"
"@character.special"     = "link:Constant"
"@comment"               = "link:Comment"
"@comment.todo.comment"  = "link:Todo"
"@conceal"               = "link:Comment"
"@conditional"           = "link:Statement"
"@constant.builtin"      = "link:Type"
"@constant"              = "link:Constant"
"@constant.macro"        = "link:Special"
"@constructor"           = "blue"
"@error"                 = "link:Error"
"@exception"             = "link:Keyword"
"@field"                 = "link:Identifier"
"@float"                 = "link:Constant"
"@function.builtin"      = "link:Function"
"@function"              = "link:Function"
"@function.macro"        = "link:PreProc"
"@include"               = "link:Include"
"@keyword.directive"     = "link:PreProc"
"@keyword.function"      = "link:Keyword"
"@keyword.import"        = "link:Include"
"@keyword"               = "link:Keyword"
"@label"                 = "link:Special"
"@method"                = "link:Function"
"@module"                = "link:Type"
"@namespace"             = "link:Statement"
"@number"                = "link:Constant"
"@operator"              = "link:Operator"
"@parameter"             = "link:Identifier"
"@preproc"               = "link:PreProc"
"@property"              = "teal1"
"@punctuation.bracket"   = "link:Delimiter"
"@punctuation.delimiter" = "link:Delimiter"
"@punctuation.special"   = "link:Special"
"@repeat"                = "link:Statement"
"@string.escape"         = "link:Special"
"@string"                = "link:String"
"@string.regexp"         = "cyan"
"@string.special"        = "link:Special"
"@string.special.path"   = "teal0"
"@tag.attribute"         = "teal1"
"@tag"                   = "blue"
"@tag.delimiter"         = "blue"
"@text"                  = "fg1"
"@text.title"            = "link:Title"
"@text.uri"              = "link:Uri"
"@text.warning"          = "link:Todo"
"@type.builtin"          = "link:Type"
"@type.definition"       = "link:Keyword"
"@type"                  = "link:Type"
"@type.qualifier"        = "link:Keyword"
"@variable.builtin"      = "link:Statement"
"@variable"              = "fg2"
"@variable.member"       = "teal1"
"@variable.parameter"    = "link:Identifier"

# Language specific highlights
"@constructor.lua"         = "link:Delimiter"
"@property.json"           = "blue"
"@property.toml"           = "blue"
"@property.yaml"           = "blue"
"@string.csv"              = "fg1"
"@variable.parameter.bash" = "fg2"

# Markup highlights
"@markup.heading.1"  = "red"
"@markup.heading.2"  = "yellow"
"@markup.heading.3"  = "green"
"@markup.heading.4"  = "teal0"
"@markup.heading.5"  = "blue"
"@markup.heading.6"  = "purple"
"@markup.list"       = "green"
"@markup.link.label" = "blue - u"
"@markup.link.url"   = "teal1 - u"
"@markup.raw"        = "link:ColorColumn"
"@markup.raw.block"  = "link:ColorColumn"

"@punctuation.special.markdown" = "link:Comment"

# Non treesitter highlights
csvCol0 = "fg2"
csvCol1 = "blue"
csvCol2 = "orange"
csvCol3 = "teal0"
csvCol4 = "purple"
csvCol5 = "green"
csvCol6 = "teal0"
csvCol7 = "yellow"
csvCol8 = "teal1"

# Plugins
BlinkCmpMenu              = "fg2 bg3"
BlinkCmpKind              = "link:Special"
BlinkCmpKindClass         = "link:Type"
BlinkCmpKindColor         = "link:Special"
BlinkCmpKindConstant      = "link:Constant"
BlinkCmpKindConstructor   = "link:@constructor"
BlinkCmpKindEnum          = "link:Constant"
BlinkCmpKindEnumMember    = "link:@property"
BlinkCmpKindEvent         = "link:Special"
BlinkCmpKindField         = "fg2"
BlinkCmpKindFile          = "fg2"
BlinkCmpKindFolder        = "link:Directory"
BlinkCmpKindFunction      = "link:Function"
BlinkCmpKindInterface     = "link:Type"
BlinkCmpKindKeyword       = "link:Keyword"
BlinkCmpKindMethod        = "link:Function"
BlinkCmpKindModule        = "link:Type"
BlinkCmpKindOperator      = "link:Operator"
BlinkCmpKindProperty      = "link:@property"
BlinkCmpKindReference     = "fg2"
BlinkCmpKindSnippet       = "link:String"
BlinkCmpKindStruct        = "link:Type"
BlinkCmpKindText          = "link:String"
BlinkCmpKindTypeParameter = "link:Identifier"
BlinkCmpKindUnit          = "link:Constant"
BlinkCmpKindValue         = "fg2"
BlinkCmpKindVariable      = "fg2"
BlinkCmpDoc               = "fg2 bg3"
BlinkCmpDocBorder         = "bg3 bg3"
BlinkCmpDocSeparator      = "fg2 bg3"
BlinkCmpLabelDeprecated   = "link:Comment"

NvimTreeFolderIcon   = "link:Directory"
NvimTreeIndentMarker = "link:Directory"
NvimTreeWindowPicker = "bg0 teal0 b"
NvimTreeRootFolder   = "purple"
NvimTreeSpecialFile  = "orange"
NvimTreeExecFile     = "green"
NvimTreeDeletedIcon  = "red"
NvimTreeGitMergeIcon = "orange"
NvimTreeGitDirtyIcon = "red"

TelescopeBorder        = "link:Comment"
TelescopeTitle         = "fg2"
TelescopePromptCounter = "link:LineNr"
TelescopeMatching      = "orange"

IblWhitespace = "link:NonText"
IblScope      = "link:LineNr"

[globals]
terminal_color_0          = "bg2"
terminal_color_1          = "red"
terminal_color_2          = "green"
terminal_color_3          = "yellow"
terminal_color_4          = "blue"
terminal_color_5          = "purple"
terminal_color_6          = "teal0"
terminal_color_7          = "fg1"
terminal_color_8          = "comment"
terminal_color_9          = "red"
terminal_color_10         = "green"
terminal_color_11         = "yellow"
terminal_color_12         = "blue"
terminal_color_13         = "purple"
terminal_color_14         = "teal0"
terminal_color_15         = "fg2"
terminal_color_background = "bg1"
terminal_color_foreground = "fg1"
