-- This file was generated by huey, do not edit

local M = {}

function M.set_highlights()
    local hl = vim.api.nvim_set_hl

    hl(0, "Normal", { fg = "#a9b1d6", bg = "#1a1b26" })
    hl(0, "NormalNC", { fg = "#a9b1d6", bg = "#1a1b26" })
    hl(0, "Cursorline", { fg = "NONE", bg = "#212433" })
    hl(0, "LineNr", { fg = "#414868", bg = "NONE" })
    hl(0, "CursorlineNr", { fg = "#e0af68", bg = "#212433" })
    hl(0, "EndOfBuffer", { fg = "#292d40", bg = "NONE" })
    hl(0, "NonText", { fg = "#292d40", bg = "NONE" })
    hl(0, "Whitespace", { fg = "#292d40", bg = "NONE" })
    hl(0, "NormalFloat", { fg = "#a9b1d6", bg = "#292d40" })
    hl(0, "Pmenu", { fg = "#a9b1d6", bg = "#292d40" })
    hl(0, "PmenuSbar", { fg = "NONE", bg = "#292d40" })
    hl(0, "PmenuSel", { fg = "#c0caf5", bg = "#414868" })
    hl(0, "PmenuThumb", { fg = "NONE", bg = "#9aa5ce" })
    hl(0, "WinSeparator", { fg = "#15161e", bg = "#15161e" })
    hl(0, "Visual", { fg = "NONE", bg = "#292d40" })
    hl(0, "StatusLine", { fg = "#9aa5ce", bg = "#15161e" })
    hl(0, "StatusLineNC", { fg = "#414868", bg = "#15161e" })
    hl(0, "Comment", { fg = "#565f89", bg = "NONE" })
    hl(0, "Constant", { fg = "#ff9e64", bg = "NONE" })
    hl(0, "Delimiter", { fg = "#9aa5ce", bg = "NONE" })
    hl(0, "Directory", { fg = "#7aa2f7", bg = "NONE" })
    hl(0, "Function", { fg = "#7aa2f7", bg = "NONE" })
    hl(0, "Identifier", { fg = "#e0af68", bg = "NONE" })
    hl(0, "Keyword", { fg = "#bb9af7", bg = "NONE" })
    hl(0, "Operator", { fg = "#c0caf5", bg = "NONE" })
    hl(0, "PreProc", { fg = "#2ac3de", bg = "NONE" })
    hl(0, "Special", { fg = "#7dcfff", bg = "NONE" })
    hl(0, "Statement", { fg = "#bb9af7", bg = "NONE" })
    hl(0, "StorageClass", { fg = "#bb9af7", bg = "NONE" })
    hl(0, "String", { fg = "#9ece6a", bg = "NONE" })
    hl(0, "Title", { fg = "#e0af68", bg = "NONE" })
    hl(0, "Type", { fg = "#73daca", bg = "NONE" })
    hl(0, "@variable", { fg = "#c0caf5", bg = "NONE" })
    hl(0, "@property", { fg = "#c0caf5", bg = "NONE" })
    hl(0, "@function.builtin", { link = "Function" })
    hl(0, "@label", { link = "Special" })
    hl(0, "@punctuation.bracket", { fg = "#9aa5ce", bg = "NONE" })
    hl(0, "@punctuation.delimiter", { fg = "#9aa5ce", bg = "NONE" })
    hl(0, "@constructor.lua", { link = "Delimiter" })
    hl(0, "xmlAttrib", { fg = "#bb9af7", bg = "NONE" })
    hl(0, "xmlAttribPunct", { fg = "#7aa2f7", bg = "NONE" })
    hl(0, "xmlEndTag", { fg = "#7aa2f7", bg = "NONE" })
    hl(0, "xmlNamespace", { fg = "#7aa2f7", bg = "NONE" })
    hl(0, "xmlTag", { fg = "#7aa2f7", bg = "NONE" })
    hl(0, "xmlTagName", { fg = "#7aa2f7", bg = "NONE" })
    hl(0, "NvimTreeFolderIcon", { link = "Directory" })
    hl(0, "NvimTreeIndentMarker", { link = "Directory" })
    hl(0, "NvimTreeWindowPicker", { fg = "#15161e", bg = "#e0af68", bold = true })
    hl(0, "NvimTreeRootFolder", { fg = "#bb9af7", bg = "NONE" })
    hl(0, "NvimTreeSpecialFile", { fg = "#ff9e64", bg = "NONE" })
    hl(0, "NvimTreeExecFile", { fg = "#9ece6a", bg = "NONE" })
    hl(0, "NvimTreeDeletedIcon", { fg = "#f7768e", bg = "NONE" })
    hl(0, "NvimTreeGitMergeIcon", { fg = "#ff9e64", bg = "NONE" })
    hl(0, "NvimTreeGitDirtyIcon", { fg = "#f7768e", bg = "NONE" })
    hl(0, "TelescopeBorder", { link = "Comment" })
    hl(0, "TelescopeTitle", { fg = "#c0caf5", bg = "NONE" })
    hl(0, "IblWhitespace", { link = "NonText" })
    hl(0, "IblScope", { link = "LineNr" })
end

function M.set_globals()
    vim.g.terminal_color_0 = "#292d40"
    vim.g.terminal_color_1 = "#f7768e"
    vim.g.terminal_color_2 = "#9ece6a"
    vim.g.terminal_color_3 = "#ff9e64"
    vim.g.terminal_color_4 = "#7aa2f7"
    vim.g.terminal_color_5 = "#bb9af7"
    vim.g.terminal_color_6 = "#7dcfff"
    vim.g.terminal_color_7 = "#a9b1d6"
    vim.g.terminal_color_8 = "#565f89"
    vim.g.terminal_color_9 = "#f7768e"
    vim.g.terminal_color_10 = "#9ece6a"
    vim.g.terminal_color_11 = "#ff9e64"
    vim.g.terminal_color_12 = "#7aa2f7"
    vim.g.terminal_color_13 = "#bb9af7"
    vim.g.terminal_color_14 = "#7dcfff"
    vim.g.terminal_color_15 = "#c0caf5"
    vim.g.terminal_color_background = "#1a1b26"
    vim.g.terminal_color_foreground = "#a9b1d6"
end

return M
