-- This file was generated by huey, do not edit

return {
    bg1 = "#1a1b26",
    bg0 = "#15161e",
    black = "#414868",
    bg2 = "#212433",
    bg3 = "#292d40",
    comment = "#565f89",
    fg0 = "#9aa5ce",
    fg1 = "#a9b1d6",
    fg2 = "#c0caf5",
    red = "#f7768e",
    green = "#9ece6a",
    yellow = "#e0af68",
    blue = "#7aa2f7",
    purple = "#bb9af7",
    cyan = "#7dcfff",
    orange = "#ff9e64",
    teal0 = "#2ac3de",
    teal1 = "#73daca",
    teal2 = "#b4f9f8",
}
